lang__name                 = "Polski" #this value has to be your own language name, translated

menu__button_start         = "Rozpocznij grę"
menu__button_load          = "Załaduj grę"
menu__button_arena         = "Arena"
menu__button_settings      = "Ustawienia"
menu__button_packs         = "Paczki"
menu__button_packs_manag   = "Menedżer Paczek"
menu__button_exit          = "Wyjdź"
menu__update               = "Aktualizacja jest dostępna!"
menu__pack_error           = "Błąd w trakcie ładowania modów"

menu__sett_general         = "Ogólne"
menu__sett_general_res     = "Rozdzielczość Ekranu"
menu__sett_general_lang    = "Język"
menu__sett_general_music   = "Głośność muzyki"
menu__sett_tech            = "Techniczne"
menu__sett_tech_legacy     = "Manualna obsługa modów"
menu__sett_tech_log_limit  = "Limit dzienników"
menu__sett_tech_log_rv     = "Usuń dzienniki"
menu__sett_tech_listbox    = "Tryb list"
menu__sett_tech_lb_amount  = "Ilość elementów list"
menu__sett_tech_lb_size    = "Wielkość elementów list"
menu__sett_tech_text_size  = "Wielkość tekstu"
menu__sett_tech_ver_notif  = "Powiadomienie o aktualizacji"
menu__sett_tech_tooltip    = "Podpowiedzi"
menu__sett_back            = "Powrót do menu"

menu__sett_tooltip_res     = "Lewy przycisk myszy zwiększa szerokość, prawy wysokość, środkowy przełącza między pełnym ekranem a oknem"
menu__sett_tooltip_lang    = "Użyj przycisków myszy żeby zmienić język"
menu__sett_tooltip_music   = "Lewy przycisk myszy by zwiększyć, prawy by zmniejszyć głośność. Środkowy przełącza między wyciszeniem a domyślną wartością"
menu__sett_tooltip_legacy  = "Wyłącza system obsługi modów przez grę. Wszystkie mody muszą być rozpakowywane manualnie"
menu__sett_tooltip_log_lm  = "Ustala limit logów. Domyślna liczba to 15"
menu__sett_tooltip_log_rv  = "Usuwa wszystkie logi"
menu__sett_tooltip_listbox = "Obecnie ta funkcja nie jest dostępna"
menu__sett_tooltip_lb_am   = "Obecnie ta funkcja nie jest dostępna"
menu__sett_tooltip_lb_size = "Obecnie ta funkcja nie jest dostępna"
menu__sett_tooltip_tx_size = "Określa rozmiar tekstu. Użyj lewego przycisku by zwiększyć, prawego by zmniejszyć"
menu__sett_tooltip_ver_nf  = "Decyduje czy powiadomienie dotyczące nowej wersji będzie widoczne w menu głównym"
menu__sett_tooltip_tooltip = "Decyduje czy podpowiedzi będą widoczne po nasunięciu na elementy interfejsu, które je wspierają"

ccrt__gen_gender   = "Płeć"
ccrt__gen_race     = "Rasa"
ccrt__gen_class    = "Klasa"
ccrt__gen_name     = "Imię"
ccrt__gen_religion = "Religia"
ccrt__gen_origin   = "Pochodzenie"
ccrt__gen_history  = "Historia"

ccrt__gen_category1        = "Płeć"
ccrt__gen_category2        = "Rasa"
ccrt__gen_category3        = "Klasa"
ccrt__gen_category4        = "Imię i awatar"
ccrt__gen_category5        = "Dystrybucja punktów"
ccrt__gen_category6        = "Religia"
ccrt__gen_category7        = "Historia postaci"
ccrt__gen_category8        = "Ustawienia rozgrywki"
ccrt__gen_category9        = "Podsumowanie"

ccrt__gender               = "Wybór płci wpływa delikatnie na dialogi oraz elementy rozgrywki."
ccrt__history              = "Napisz swoją historię"
ccrt__name_input           = "Wprowadź imię"
ccrt__url_check            = "Użyj linku"
ccrt__dir_check            = "Użyj pliku"
ccrt__lore_check           = "Przeglądaj domyślne"
ccrt__av_clear             = "Wyczyść"

ccrt__tooltip_name         = "Wpisz imię lub wybierz z listy po lewej"
ccrt__tooltip_av_lib       = "Wybierz awatar swojej rasy - użyj strzałek by przeglądać. Jeśli opcja jest wyszarzona, twoja rasa nie posiada awatarów"
ccrt__tooltip_av_url       = "Pobierz obraz z linku. Link powinien prowadzić do obrazu JPG/PNG/WEBP (link jest poprawny jeśli zawiera rozszerzenie)"
ccrt__tooltip_av_dir       = "Kopiuj obraz z komputera. Ścieżka powinna być kompletna i zawierać obraz wraz z rozszerzeniem. Wspierane są formaty JPG i PNG"

ccrt__name_exists          = "To imię już jest w użyciu"
ccrt__sett_hardcore        = "Permanentna śmierć"
ccrt__sett_hardcore_descr  = "Zablokuje grę po śmierci, uniemożliwiając Ci załadowanie jej."
ccrt__end_name             = "Imię"
ccrt__end_race             = "Rasa"
ccrt__end_class            = "Klasa"
ccrt__end_religion         = "Religia"
ccrt__end_origin           = "Historia"
ccrt__end_save             = "Zapisz"
ccrt__end_save_warn        = '''
Postać nie będzie dostępna w obecnej wersji, jednak będzie można ją załadować w przyszłości
'''

load__packs_used      = "Użyte mody"
load__load            = "Załaduj grę"
load__restore         = "Nadpisz ze schowka"
load__remove          = "Usuń grę"
load__error           = "Błąd podczas ładowania gry"

pack__type_stats      = "Statpack"
pack__type_themes     = "Themepack"
pack__type_worlds     = "Worldpack"
pack__name            = "Nazwa"
pack__authors         = "Autorzy"
pack__version         = "Wersja"
pack__descr           = "Opis"
pack__req             = "Wymagane paczki"

pack__switch          = "Wyłącz/włącz"
pack__disabled        = "Paczka wyłączona"
pack__move_up         = "Przenieś w górę"
pack__move_down       = "Przenieś w dół"
pack__url             = "Strona internetowa"
pack__remove          = "Usuń paczkę"

pack__tooltip_switch  = "Zawartość wyłączonych paczek nie będzie dostępna w trakcie gry"
pack__tooltip_mvu     = "Przenosi paczkę w górę hierarchii. Kolejność ładowania wpływa na nadpisywanie, zatem paczki opierające się na innych powinny być pod nimi"
pack__tooltip_mvd     = "Przenosi paczkę w dół hierarchii. Kolejność ładowania wpływa na nadpisywanie, zatem paczki opierające się na innych powinny być pod nimi"

loc__bt_character = "Statystyki"
loc__bt_inventory = "Ekwipunek"
loc__bt_location  = "Lokacja"
loc__bt_map       = "Mapa"
loc__bt_diary     = "Dziennik"
# end

menu__load_choose          = "Wybierz swój zapis gry"
menu__load_choose_hint     = "[użyj numeru lub dokładnej nazwy]"
menu__load_save_deleted    = "Zapis gry usunięty!"
menu__load_save_unsaved    = "Zapis gry nie był poprawnie zapisany. Nadpisywanie z systemu."
menu__load_action1         = "[użyj dowolnego niewskazanego klawisza, żeby wrócić do menu]" #will be removed
menu__load_action2         = "[użyj '/' przed nazwą zapisu gry, żeby go usunąć]" #will be removed
menu__settings_choose      = "Zmień ustawienie"
menu__settings_action      = "[użyj dowolnego nie-numerycznego klawisza, żeby wrócić do menu]" #will be removed
menu__warn_core_missing    = "Podstawowe pliki nie zostały załadowane! Ograniczone opcje menu."

pack__general_info         = "ZAŁADOWANE PACZKI"
pack__actions_opt1         = "Wpisz nazwę paczki, żeby otworzyć jej opcje"
pack__actions_opt2         = "Użyj klucza -unzip- żeby wypakować pliki moda" #this should be deprecated eventually (or made greyed out button if autoimport is on)
pack__actions_opt3         = "Użyj -q- żeby wyjść do menu"
pack__lister_id            = "ID Paczki"
pack__lister_type          = "Typ"
pack__lister_credits       = "Zasługi"
pack__lister_disabled      = "Paczka nieaktywna"
pack__lister_action1       = "[link] Otwórz link"
pack__lister_action2       = "[switch] Zmień status moda (aktywny/nieaktywny)"
pack__lister_action3       = "[q] Powróć do listy paczek"
pack__error_not_exist      = "Paczka z tą nazwą nie istnieje!"

game__init_charname        = "Wpisz imię swojej postaci"
game__init_charname_rv     = "Wpisz -0- żeby anulować"
game__init_gender          = "Wybierz płeć"
game__init_race            = "Wybierz rasę"
game__init_class           = "Wybierz klasę"
game__init_class_excl      = "Klasa jest ekskluzywna dla rasy, której nie reprezentujesz!" #will be removed, it is here just bc I'm dumb
game__init_attr            = "Wybierz cechę, którą chcesz wzmocnić"
game__init_skill           = "Wybierz umiejętność, którą chcesz wzmocnić"

stat__gen_name             = "Imię"
stat__gen_gender           = "Płeć"
stat__gen_gender1          = "Mężczyzna"
stat__gen_gender2          = "Kobieta"
stat__gen_location         = "Lokacja"

stat__hint_hp              = "Punkty życia"
stat__hint_mp              = "Punkty magii"
stat__hint_sp              = "Energia"
stat__hint_xp              = "Doświadczenie"
stat__hint_weight          = "Ciężar"
stat__hint_xp_required     = "Doświadczenie do następnego poziomu"
stat__hint_level           = "Poziom"
stat__hint_pwr_tech        = "Wartość siły: Technologia"
stat__hint_pwr_magic       = "Wartość siły: Magia"
stat__hint_pwr_conn        = "Wartość siły: Połączenie"
stat__hint_pwr_void        = "Wartość siły: Pustka"
stat__hint_pwm_diamond     = "Modyfikator siły: Negacja kary strukturalnej"
stat__hint_pwm_moon        = "Modyfikator siły: Negacja kary harmonicznej"
stat__hint_armour          = "Pancerz"

stat__perk_assassin_hit    = "Zabójczy cios"
stat__perk_trader_sight    = "Wzrok kupca"
stat__perk_vehicle_driving = "Kierowanie pojazdami"
stat__perk_toxin_immunity  = "Odporność na toksyny"
stat__perk_animal_friend   = "Przyjaciel zwierząt"
stat__perk_animal_trainer  = "Trenowanie zwierząt"
stat__perk_berserk         = "Berserker"
stat__perk_step_on_water   = "Chodzący po wodzie"
stat__perk_flying_monk     = "Latający mnich"
stat__perk_vampirism       = "Wampiryzm"
stat__perk_ritual_tongue   = "Języki rytualne"
stat__perk_ancient_tongue  = "Język starożytnych architektów"

gen__enabled               = "Włączone"
gen__disabled              = "Wyłączone"
gen__proportional          = "Proporcjonalne"
gen__sized                 = "Rozmiarowe"

system__text_load_fail     = "Tekst nie mógł się załadować"